[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://crm-app-qsz1.onrender.com/api"
  REACT_APP_USE_MOCKS = "false"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200