services:
  - type: web
    name: crm-app-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://itsivali.github.io
    healthCheckPath: /api/health
    autoDeploy: true